name: Deploy

on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download terraform
        run: wget https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip
      - name: extract terraform
        run: unzip terraform_1.5.2_linux_amd64.zip
      - name: Find Version
        run:  terraform -version
      - name: copy file
        run:  sudo cp "terraform"  "/usr/local/bin"  
  eks-deploy:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        working-directory: ./NEWGitHUB
        env:
          CI: true
        run: |
          pwd
      - uses: hashicorp/setup-terraform@v2
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -input=false
