name: First Workflow
on: workflow_dispatch

jobs:
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
            - name: Terraform Init
              id: init
              run: terraform init
            - name: Terraform Plan
              run: terraform plan -no-color -lock=false 
            - name: Terraform Apply
              run: terraform apply --auto-approve -lock=false
            - name: Terraform destroy
              run: terraform destroy --auto-approve -lock=false
