name: First Workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download terraform
        run: wget https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip
      - name: extract terraform
        run: unzip terraform_1.5.2_linux_amd64.zip
      - name: Find Version
        run:  terraform -version
      - name: copy file
        run:  sudo cp "terraform"  "/usr/local/bin"  
  terraform_EKS_Deployment:
     needs: first-job
     runs-on: ubuntu-latest
     steps:
         - uses: actions/checkout@v1
         - name: Terraform init
           env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         - name: Echo an expression
           run: echo "The current date is ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
         - name: Terraform
           run: |
                terraform init 
                terraform apply --auto-approve 
