name: First Workflow
on: workflow_dispatch

jobs:
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        steps:
            - name: Terraform destroy
              run: terraform destroy --auto-approve -lock=false
